export enum NotificationType {
  NEW_SESSION_STARTED = 'NEW_SESSION_STARTED',
  NEW_PHASE_STARTED = 'NEW_PHASE_STARTED',
  POINTS_SETUP = 'POINTS_SETUP',
  FIRST_VICTORY = 'FIRST_VICTORY',
  DEUS_EX_MACHINA = 'DEUS_EX_MACHINA',
  LAST_VICTORY = 'LAST_VICTORY',
  END_OF_SESSION = 'END_OF_SESSION'
}
